name: location_picker_flutter_map
description: Package that provides Place search and Location picker for flutter maps with a lot of customizations using Open Street Map
version: 3.1.0
homepage: https://github.com/Michael-M-aher/location_picker_flutter_map

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.0.0
  location: ^8.0.0
  http: ^1.3.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  flutter_map_location_marker: ^9.1.1
  flutter_map_cancellable_tile_provider: ^3.1.0



dependency_overrides:
  flutter_map: ^7.0.0
  
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter